// const sequelize = require('../config/connection')
const Movie = require('../models/Movie');



const movies = [
    {
        title: 'The Lion King',
        rating: 9.00,
        genre: 'Family',
        plot: 'A family of lions get up to some real shit',
        poster_path: 'https://images.moviesanywhere.com/c07276e9473360730fdbc94baebc4236/4692c964-61ba-486d-9c77-939dbfba2f07.jpg', 
        release_year: 1994,
    },
    {
        title: 'Forrst Gump',
        rating: 8.50,
        genre: 'Drama',
        plot: 'Forrest goes everywhere',
        poster_path: 'https://m.media-amazon.com/images/I/81xTx-LxAPL._SL1500_.jpg',
        release_year: 1994,
    },
    {
        title: 'Kill Bill: Vol. 1',
        rating: 7.90,
        genre: 'Action',
        plot: 'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.',
        poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',
        release_year: 2003,
    },
    {
        title: 'Pulp Fiction',
        rating: 8.40,
        genre: 'Action',
        plot: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        release_year: 1994,
    },
    {
        title: 'Inglourious Basterds',
        rating: 8.2,
        genre: 'Action',
        plot: "In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as 'The Bastards' are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.",
        poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        release_year: 2009,
    },
    {
        title: 'Jackie Brown',
        rating: 7.35,
        genre: 'Drama',
        plot: "Jackie Brown is a flight attendant who gets caught in the middle of smuggling cash into the country for her gunrunner boss. When the cops try to use Jackie to get to her boss, she hatches a plan — with help from a bail bondsman — to keep the money for herself.",
        poster_path: "/ewbLUXvm4riZL0aepy90o0vMesn.jpg",
        release_year: 1997,
    },
    {
        title: "Taxi Driver",
        rating: 8.18,
        genre: 'Thriller',
        plot: "A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feed his urge for violent action, attempting to save a preadolescent prostitute in the process.",
        poster_path: "/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
        release_year: 1976,
    },
    {
        title: "GoodFellas",
        rating: 8.45,
        genre: 'Drama',
        plot: "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
        poster_path: "/6QMSLvU5ziIL2T6VrkaKzN2YkxK.jpg",
        release_year: 1990,
    },
    {
        title: "A Clockwork Orange",
        rating: 8.22,
        genre: 'Thriller',
        plot: "In a near-future Britain, young Alexander DeLarge and his pals get their kicks beating and raping anyone they please. When not destroying the lives of others, Alex swoons to the music of Beethoven. The state, eager to crack down on juvenile crime, gives an incarcerated Alex the option to undergo an invasive procedure that'll rob him of all personal agency. In a time when conscience is a commodity, can Alex change his tune?",
        poster_path:  "/4sHeTAp65WrSSuc05nRBKddhBxO.jpg",
        release_year: 1971,
    },
    {
        title: "Scarface",
        rating: 8.15,
        genre: 'Action',
        plot: "After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, controlling nearly all the cocaine that comes through Miami. But increased pressure from the police, wars with Colombian drug cartels and his own drug-fueled paranoia serve to fuel the flames of his eventual downfall.",
        poster_path: "/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg",
        release_year: 1983,
    },
    {
        title: "The Usual Suspects",
        rating: 8.21,
        genre: 'Thriller',
        plot: "Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.",
        poster_path: "/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg",
        release_year: 1995,
    },
    {
        title: "Memento",
        rating: 8.19,
        genre: 'Drama',
        plot: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
        poster_path: "/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
        release_year: 2000,
    },
    {
        title: "The Silence of the Lambs",
        rating: 8.32,
        genre: 'Thriller',
        plot: "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
        poster_path: "/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
        release_year: 1991,
    },
    {
        title: "One Flew Over the Cuckoo's Nest",
        rating: 8.42,
        genre: 'Drama',
        plot: "While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.",
        poster_path: "/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
        release_year: 1975,
    },
    {
        title: "American Beauty",
        rating: 8.00,
        genre: 'Drama',
        plot: "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
        poster_path: "/wby9315QzVKdW9BonAefg8jGTTb.jpg",
        release_year: 1999,
    },
    {
        title: "Saving Private Ryan",
        rating: 8.18,
        genre: 'Action',
        plot: "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
        poster_path: "/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
        release_year: 1998,
    },
    {
        title: "The Truman Show",
        rating: 8.09,
        genre: 'Drama',
        plot: "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV show that broadcasts every aspect of his life without his knowledge. His entire life has been an unending soap opera for consumption by the rest of the world. And everyone he knows, including his wife and his best friend is really an actor, paid to be part of his life.",
        poster_path: "/e5EMJEQnWkWb8G6sTMkN91qiqUz.jpg",
        release_year: 1998,
    },
    {
        title: "The Green Mile",
        rating: 8.50,
        genre: 'Drama',
        plot: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        release_year: 1999,
    },
    {
        title: "12 Angry Men",
        rating: 8.50,
        genre: 'Drama',
        plot: "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        poster_path: "/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg",
        release_year: 1957,
    },
    {
        title: "The Dark Knight",
        rating: 8.50,
        genre: 'Action',
        plot: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        release_year: 2008,
    },
    {
        title: "The Lord of the Rings: The Return of the King",
        rating: 8.50,
        genre: 'Adventure',
        plot: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
        poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        release_year: 2003,
    },
    {
        title: "Star Wars: The Empire Strikes Back",
        rating: 8.40,
        genre: 'Adventure',
        plot: "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
        poster_path: "/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
        release_year: 1980,
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        rating: 8.4,
        genre: 'Adventure',
        plot: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
        poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        release_year: 2001,
    },
    {
        title: "The Lord of the Rings: The Two Towers",
        rating: 8.3,
        genre: 'Adventure',
        plot: "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
        poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
        release_year: 2002,
    },
    {
        title: "The Suicide Squad",
        rating: 8.10,
        genre: '',
        plot: "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        poster_path: "/iCi4c4FvVdbaU1t8poH1gvzT6xM.jpg",
        release_year: 2021,
    },
    {
        title: "Star Wars: The Last Jedi",
        rating: 6.90,
        genre: 'Adventure',
        plot: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
        poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
        release_year: 2017,
    },
    {
        title: "Orphan",
        rating: 6.90,
        genre: 'Horror',
        plot: "After losing their baby, a married couple adopt 9-year old Esther, who may not be as innocent as she seems.",
        poster_path: "/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg",
        release_year: 2009,
    },
    {
        title: "Cars 2",
        rating: 5.8,
        genre: 'Family',
        plot: "Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.",
        poster_path: "/okIz1HyxeVOMzYwwHUjH2pHi74I.jpg",
        release_year: 2011,
    },
    {
        title: "Monsters University",
        rating: 7.00,
        genre: 'Family',
        plot: "A look at the relationship between Mike and Sulley during their days at Monsters University — when they weren't necessarily the best of friends.",
        poster_path: "/upaMBEonGeZGQc3xtUVZOfe1lGl.jpg",
        release_year: 2013,
    },
    {
        title: "Princess Mononoke",
        rating: 8.35,
        genre: 'Family',
        plot: "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
        poster_path: "/jHWmNr7m544fJ8eItsfNk8fs2Ed.jpg",
        release_year: 1997,
    },
];

const seedMovies = () => Movie.bulkCreate(movies)
seedMovies();

module.exports= seedMovies;


// {
//     title: 
//     rating: ,
//     genre: '',
//     plot: 
//     poster_path: 
//     release_year: ,
// },