// const sequelize = require('../config/connection')
const Movie = require('../models/Movie');



const movies = [

    {
        title: 'Kill Bill: Vol. 1',
        rating: 7.9,
        genre: 'Action',
        plot: 'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.',
        poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',
        release_year: 2003,
    },
    {
        title: 'Pulp Fiction',
        rating: 8.4,
        genre: 'Action',
        plot: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        release_year: 1994,
    },
    {
        title: 'Inglourious Basterds',
        rating: 8.2,
        genre: 'Action',
        plot: "In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as 'The Bastards' are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.",
        poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        release_year: 2009,
    },
    {
        title: 'Jackie Brown',
        rating: 7.4,
        genre: 'Drama',
        plot: "Jackie Brown is a flight attendant who gets caught in the middle of smuggling cash into the country for her gunrunner boss. When the cops try to use Jackie to get to her boss, she hatches a plan — with help from a bail bondsman — to keep the money for herself.",
        poster_path: "/ewbLUXvm4riZL0aepy90o0vMesn.jpg",
        release_year: 1997,
    },
    {
        title: "Taxi Driver",
        rating: 8.2,
        genre: 'Thriller',
        plot: "A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feed his urge for violent action, attempting to save a preadolescent prostitute in the process.",
        poster_path: "/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
        release_year: 1976,
    },
    {
        title: "GoodFellas",
        rating: 8.5,
        genre: 'Drama',
        plot: "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
        poster_path: "/6QMSLvU5ziIL2T6VrkaKzN2YkxK.jpg",
        release_year: 1990,
    },
    {
        title: "A Clockwork Orange",
        rating: 8.2,
        genre: 'Thriller',
        plot: "In a near-future Britain, young Alexander DeLarge and his pals get their kicks beating and raping anyone they please. When not destroying the lives of others, Alex swoons to the music of Beethoven. The state, eager to crack down on juvenile crime, gives an incarcerated Alex the option to undergo an invasive procedure that'll rob him of all personal agency. In a time when conscience is a commodity, can Alex change his tune?",
        poster_path:  "/4sHeTAp65WrSSuc05nRBKddhBxO.jpg",
        release_year: 1971,
    },
    {
        title: "Scarface",
        rating: 8.1,
        genre: 'Action',
        plot: "After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, controlling nearly all the cocaine that comes through Miami. But increased pressure from the police, wars with Colombian drug cartels and his own drug-fueled paranoia serve to fuel the flames of his eventual downfall.",
        poster_path: "/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg",
        release_year: 1983,
    },
    {
        title: "The Usual Suspects",
        rating: 8.2,
        genre: 'Thriller',
        plot: "Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.",
        poster_path: "/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg",
        release_year: 1995,
    },
    {
        title: "Memento",
        rating: 8.2,
        genre: 'Drama',
        plot: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
        poster_path: "/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
        release_year: 2000,
    },
    {
        title: "The Silence of the Lambs",
        rating: 8.3,
        genre: 'Thriller',
        plot: "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
        poster_path: "/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
        release_year: 1991,
    },
    {
        title: "One Flew Over the Cuckoo's Nest",
        rating: 8.4,
        genre: 'Drama',
        plot: "While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.",
        poster_path: "/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
        release_year: 1975,
    },
    {
        title: "American Beauty",
        rating: 8.0,
        genre: 'Drama',
        plot: "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
        poster_path: "/wby9315QzVKdW9BonAefg8jGTTb.jpg",
        release_year: 1999,
    },
    {
        title: "Saving Private Ryan",
        rating: 8.2,
        genre: 'Action',
        plot: "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
        poster_path: "/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
        release_year: 1998,
    },
    {
        title: "The Truman Show",
        rating: 8.1,
        genre: 'Drama',
        plot: "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV show that broadcasts every aspect of his life without his knowledge. His entire life has been an unending soap opera for consumption by the rest of the world. And everyone he knows, including his wife and his best friend is really an actor, paid to be part of his life.",
        poster_path: "/e5EMJEQnWkWb8G6sTMkN91qiqUz.jpg",
        release_year: 1998,
    },
    {
        title: "The Green Mile",
        rating: 8.5,
        genre: 'Drama',
        plot: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        release_year: 1999,
    },
    {
        title: "12 Angry Men",
        rating: 8.5,
        genre: 'Drama',
        plot: "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        poster_path: "/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg",
        release_year: 1957,
    },
    {
        title: "The Dark Knight",
        rating: 8.5,
        genre: 'Action',
        plot: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        release_year: 2008,
    },
    {
        title: "The Lord of the Rings: The Return of the King",
        rating: 8.5,
        genre: 'Adventure',
        plot: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
        poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        release_year: 2003,
    },
    {
        title: "Star Wars: The Empire Strikes Back",
        rating: 8.4,
        genre: 'Adventure',
        plot: "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
        poster_path: "/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
        release_year: 1980,
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        rating: 8.4,
        genre: 'Adventure',
        plot: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
        poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        release_year: 2001,
    },
    {
        title: "The Lord of the Rings: The Two Towers",
        rating: 8.3,
        genre: 'Adventure',
        plot: "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
        poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
        release_year: 2002,
    },
    {
        title: "The Suicide Squad",
        rating: 8.1,
        genre: '',
        plot: "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        poster_path: "/iCi4c4FvVdbaU1t8poH1gvzT6xM.jpg",
        release_year: 2021,
    },
    {
        title: "Star Wars: The Last Jedi",
        rating: 6.9,
        genre: 'Adventure',
        plot: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
        poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
        release_year: 2017,
    },
    {
        title: "Orphan",
        rating: 6.9,
        genre: 'Horror',
        plot: "After losing their baby, a married couple adopt 9-year old Esther, who may not be as innocent as she seems.",
        poster_path: "/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg",
        release_year: 2009,
    },
    {
        title: "Cars 2",
        rating: 5.8,
        genre: 'Family',
        plot: "Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.",
        poster_path: "/okIz1HyxeVOMzYwwHUjH2pHi74I.jpg",
        release_year: 2011,
    },
    {
        title: "Monsters University",
        rating: 7.0,
        genre: 'Family',
        plot: "A look at the relationship between Mike and Sulley during their days at Monsters University — when they weren't necessarily the best of friends.",
        poster_path: "/upaMBEonGeZGQc3xtUVZOfe1lGl.jpg",
        release_year: 2013,
    },
    {
        title: "Princess Mononoke",
        rating: 8.4,
        genre: 'Family',
        plot: "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
        poster_path: "/jHWmNr7m544fJ8eItsfNk8fs2Ed.jpg",
        release_year: 1997,
    },
    {
        title: "Mulan",
        rating: 7.9,
        genre: 'Family',
        plot: "A tomboyish girl disguises herself as a young man so she can fight with the Imperial Chinese Army against the invading Huns. With help from wise-cracking dragon Mushu, Mulan just might save her country -- and win the heart of handsome Captain Li Shang.",
        poster_path: "/bJ0DxWQDLdjSJmFHwtximVdgJ5P.jpg",
        release_year: 1998,
    },
    {
        title: "A Bug's Life",
        rating: 6.9,
        genre: 'Family',
        plot: "On behalf of 'oppressed bugs everywhere', an inventive ant named Flik hires a troupe of warrior bugs to defend his bustling colony from a horde of freeloading grasshoppers led by the evil-minded Hopper.",
        poster_path: "/hFamOus53922agTlKxhcL7ngJ9h.jpg",
        release_year: 1998,
    },
    {
        title: "The Lego Movie",
        rating: 7.4,
        genre: 'Family',
        plot: "An ordinary Lego mini-figure, mistakenly thought to be the extraordinary MasterBuilder, is recruited to join a quest to stop an evil Lego tyrant from gluing the universe together.",
        poster_path: "/lbctonEnewCYZ4FYoTZhs8cidAl.jpg",
        release_year: 2014,
    },
    {
        title: "Madagascar",
        rating: 6.8,
        genre: 'Family',
        plot: "Alex the lion is the king of the urban jungle, the main attraction at New York's Central Park Zoo. He and his best friends—Marty the zebra, Melman the giraffe and Gloria the hippo—have spent their whole lives in blissful captivity before an admiring public and with regular meals provided for them. Not content to leave well enough alone, Marty lets his curiosity get the better of him and makes his escape—with the help of some prodigious penguins—to explore the world.",
        poster_path: "/uHkmbxb70IQhV4q94MiBe9dqVqv.jpg",
        release_year: 2005,
    },
    {
        title: "Bee Movie",
        rating: 5.9,
        genre: 'Family',
        plot: "Barry B. Benson, a bee who has just graduated from college, is disillusioned at his lone career choice: making honey. On a special trip outside the hive, Barry's life is saved by Vanessa, a florist in New York City. As their relationship blossoms, he discovers humans actually eat honey, and subsequently decides to sue us.",
        poster_path: "/rYBaXgvTKFS8iZC7Wr8SMomSauQ.jpg",
        release_year: 2007,
    },
    {
        title: "The Hunger Games",
        rating: 7.1,
        genre: 'Adventure',
        plot: "Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games.  Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains.  Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy.  If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
        poster_path: "/iQK0pkTQC60XR3Zlu2pp8kujoqW.jpg",
        release_year: 2012,
    },
    {
        title: "Lilo & Stitch",
        rating: 7.5,
        genre: 'Family',
        plot: "As Stitch, a runaway genetic experiment from a faraway planet, wreaks havoc on the Hawaiian Islands, he becomes the mischievous adopted alien 'puppy' of an independent little girl named Lilo and learns about loyalty, friendship, and 'ohana, the Hawaiian tradition of family.",
        poster_path: "/d73UqZWyw3MUMpeaFcENgLZ2kWS.jpg",
        release_year: 2002,
    },
    {
        title: "Cars",
        rating: 6.8,
        genre: 'Family',
        plot: "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster_path: "/abW5AzHDaIK1n9C36VdAeOwORRA.jpg",
        release_year: 2006,
    },
    {
        title: "The SpongeBob SquarePants Movie",
        rating: 6.9,
        genre: 'Comedy',
        plot: "There's trouble brewing in Bikini Bottom. Someone has stolen King Neptune's crown, and it looks like Mr. Krab, SpongeBob's boss, is the culprit. Though he's just been passed over for the promotion of his dreams, SpongeBob stands by his boss, and along with his best pal Patrick, sets out on a treacherous mission to Shell City to reclaim the crown and save Mr. Krab's life.",
        poster_path: "/6sgo6TCakeL4KFwwcJyvkZ7zhMX.jpg",
        release_year: 2004,
    },
    {
        title: "Minions",
        rating: 6.3,
        genre: 'Family',
        plot: "Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.",
        poster_path: "/vlOgaxUiMOA8sPDG9n3VhQabnEi.jpg",
        release_year: 2015,
    },
    {
        title: "Moana",
        rating: 7.5,
        genre: 'Family',
        plot: "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the demigod to set things right.",
        poster_path: "/4JeejGugONWpJkbnvL12hVoYEDa.jpg",
        release_year: 2016,
    },
    {
        title: "Cars 3",
        rating: 6.8,
        genre: 'Family',
        plot: "Blindsided by a new generation of blazing-fast racers, the legendary Lightning McQueen is suddenly pushed out of the sport he loves. To get back in the game, he will need the help of an eager young race technician with her own plan to win, inspiration from the late Fabulous Hudson Hornet, and a few unexpected turns. Proving that #95 isn't through yet will test the heart of a champion on Piston Cup Racing’s biggest stage!",
        poster_path: "/jJ8TnHvWHaVadW5JJjGYsM07j9i.jpg",
        release_year: 2017,
    },
    {
        title: "Spider-Man",
        rating: 7.1,
        genre: 'Adventure',
        plot: "After being bitten by a genetically altered spider, nerdy high school student Peter Parker is endowed with amazing powers to become the Amazing superhero known as Spider-Man.",
        poster_path: "/fwoETElxZqiF3it8F4HitSliXqp.jpg",
        release_year: 2002,
    },
    {
        title: "Monsters, Inc.",
        rating: 7.8,
        genre: 'Family',
        plot: "James Sullivan and Mike Wazowski are monsters, they earn their living scaring children and are the best in the business... even though they're more afraid of the children than they are of them. When a child accidentally enters their world, James and Mike suddenly find that kids are not to be afraid of and they uncover a conspiracy that could threaten all children across the world.",
        poster_path: "/sgheSKxZkttIe8ONsf2sWXPgip3.jpg",
        release_year: 2001,
    },
    {
        title: "Titanic",
        rating: 7.8,
        genre: 'Drama',
        plot: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
        poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        release_year: 1997,
    },
    {
        title: "The Exorcist",
        rating: 7.7,
        genre: 'Horror',
        plot: "12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.",
        poster_path: "/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg",
        release_year: 1973,
    },
    {
        title: "Hereditary",
        rating: 7.1,
        genre: 'Horror',
        plot: "When Ellen, the matriarch of the Graham family, passes away, her daughter's family begins to unravel cryptic and increasingly terrifying secrets about their ancestry.",
        poster_path: "/lHV8HHlhwNup2VbpiACtlKzaGIQ.jpg",
        release_year: 2018,
    },
    {
        title: "The Nun",
        rating: 5.8,
        genre: 'Horror',
        plot: "When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together they uncover the order’s unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of the same demonic nun that first terrorized audiences in “The Conjuring 2” as the abbey becomes a horrific battleground between the living and the damned.",
        poster_path: "/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg",
        release_year: 2018,
    },
    {
        title: "Ouija: Origin of Evil",
        rating: 6.0,
        genre: 'Horror',
        plot: "In 1965 Los Angeles, a widowed mother and her two daughters add a new stunt to bolster their séance scam business and unwittingly invite authentic evil into their home. When the youngest daughter is overtaken by the merciless spirit, this small family confronts unthinkable fears to save her and send her possessor back to the other side.",
        poster_path: "/cAZk4y7JZswALX6nTf5KXNjPMUE.jpg",
        release_year: 2016,
    },
    {
        title: "The Devil Inside",
        rating: 4.8,
        genre: 'Horror',
        plot: "In Italy, a woman becomes involved in a series of unauthorized exorcisms during her mission to discover what happened to her mother, who allegedly murdered three people during her own exorcism.",
        poster_path: "/mtyFRIRBmrCE2XKU5EnEK8dtu2X.jpg",
        release_year: 2012,
    },
    {
        title: "Paranormal Activity",
        rating: 5.9,
        genre: 'Horror',
        plot: "After a young, middle-class couple moves into what seems like a typical suburban house, they become increasingly disturbed by a presence that may or may not be demonic but is certainly the most active in the middle of the night.  Followed by five terrifying installments in the franchise, this is the original found-footage shocker that started it all.",
        poster_path: "/1bjA7de4O0NhMsaOqwvrecophUs.jpg",
        release_year: 2009,
    },
    {
        title: "Halloween",
        rating: 6.1,
        genre: 'Horror',
        plot: "After being committed for 17 years, Michael Myers, now a grown man and still very dangerous, escapes from the mental institution (where he was committed as a 10 year old) and he immediately returns to Haddonfield, where he wants to find his baby sister, Laurie. Anyone who crosses his path is in mortal danger",
        poster_path: "/kX0tl6NyfLw1N2vegNEVO0SNZAg.jpg",
        release_year: 2007,
    },
    {
        title: "Friday the 13th",
        rating: 6.3,
        genre: 'Horror',
        plot: "Camp counselors are stalked and murdered by an unknown assailant while trying to reopen a summer camp that was the site of a child's drowning.",
        poster_path: "/4nbUlVEg31I8lchI3bu3Oq3Ks4t.jpg",
        release_year: 1980,
    },
    {
        title: "Friday the 13th Part 2",
        rating: 6.1,
        genre: 'Horror',
        plot: "Five years after the horrible bloodbath at Camp Crystal Lake, it seems Jason Voorhees and his demented mother are in the past. Paul opens up a new camp close to the infamous site, ignoring warnings to stay away, and a sexually-charged group of counselors follow -- including child psychologist major Ginny. But Jason has been hiding out all this time, and now he's ready for revenge.",
        poster_path: "/zgcWEU9JbNHnE8b8TcxFvWjPRUp.jpg",
        release_year: 1981,
    },
    // {
    //     title: "Friday the 13th Part III",
    //     rating: 5.8,
    //     genre: '"/mYkbmw6umfbvPYBwkcOJsKbTCQ1.jpg",',
    //     plot: "An idyllic summer turns into a nightmare of unspeakable terror for yet another group of naive counselors. Ignoring Camp Crystal Lake's bloody legacy, one by one they fall victim to the maniacal Jason who stalks them at every turn.",
    //     poster_path: 'cant find',
    //     release_year: 1982,
    // },
    {
        title: "Friday the 13th: The Final Chapter",
        rating: 6.0,
        genre: 'Horror',
        plot: "After being mortally wounded and taken to the morgue, murderer Jason Voorhees spontaneously revives and embarks on a killing spree as he makes his way back to his home at Crystal Lake.",
        poster_path: "/5KRBkaF6PdorcFjWiDY4tJy67Jf.jpg",
        release_year: 1984,
    },
    {
        title: "Friday the 13th: A New Beginning",
        rating: 5.2,
        genre: '',
        plot: "Homicidal maniac Jason returns from the grave to cause more bloody mayhem. Young Tommy may have escaped from Crystal Lake, but he’s still haunted by the gruesome events that happened there. When gory murders start happening at the secluded halfway house for troubled teens where he now lives, it seems like his nightmarish nemesis, Jason, is back for more sadistic slaughters.",
        poster_path: "/oh99gL4Yu3C7cIsRZ5vNaHdSt1R.jpg",
        release_year: 1985,
    },
    {
        title: "Friday the 13th Part VI: Jason Lives",
        rating: 6.1,
        genre: 'Horror',
        plot: "Determined to finish off the infamous killer Jason Voorhees once and for all, Tommy Jarvis and a friend exhume Jason’s corpse in order to cremate him. Things go awry when Jason is instead resurrected, sparking a new chain of ruthlessly brutal murders. Now it’s up to Tommy to stop the dark, devious and demented deaths that he unwittingly brought about.",
        poster_path: "/527lL7kLmvxLXnMoaMrKashaC58.jpg",
        release_year: 1986,
    },
    {
        title: "Friday the 13th Part VII: The New Blood",
        rating: 5.4,
        genre: 'Horror',
        plot: "A young girl who possesses the power of telekinesis accidentally causes her father's death after a family dispute at Crystal Lake. Years later, when a doctor tries to exploit her abilities, her power becomes a hellish curse, and she unwittingly unchains the merciless, bloodthirsty Jason Voorhees from his watery grave.",
        poster_path: "/2Tyr422N8ivi9TfA9BAP896Z6Q.jpg",
        release_year: 1988,
    },
    {
        title: "Friday the 13th Part VIII: Jason Takes Manhattan",
        rating: 4.9,
        genre: 'Horror',
        plot: "A group of students on a graduation cruise bound for Manhattan soon realize they've got a stowaway aboard the ship: serial killer Jason Voorhees.",
        poster_path: "/s5U5JgPpgfTnbGxQF2bOlfqqz5b.jpg",
        release_year: 1989,
    },
    {
        title: "Jason Goes to Hell: The Final Friday",
        rating: 4.4,
        genre: 'Horror',
        plot: "Jason Voorhees, the living, breathing essence of evil, is back for one fierce, final fling! Tracked down and blown to bits by a special FBI task force, everyone now assumes that he's finally dead. But everybody assumes wrong. Jason has been reborn with the bone-chilling ability to assume the identity of anyone he touches. The terrifying truth is that he could be anywhere, or anybody. In this shocking, blood-soaked finale to Jason's carnage-ridden reign of terror, the horrible secret of his unstoppable killing instinct is finally revealed.",
        poster_path: "/Aacq05foqiWdXqetFv02HBvMoJy.jpg",
        release_year: 1993,
    },
    {
        title: "Anchorman 2: The Legend Continues",
        rating: 6.0,
        genre: 'Comedy',
        plot: "With the 70s behind him, San Diego's top rated newsman, Ron Burgundy, returns to take New York's first 24-hour news channel by storm.",
        poster_path: "/55volAzeebtFzyrx7DJkegvw8Ta.jpg",
        release_year: 2013,
    },
    {
        title: "Austin Powers: The Spy Who Shagged Me",
        rating: 6.2,
        genre: 'Comedy',
        plot: "When diabolical genius Dr. Evil travels back in time to steal superspy Austin Powers's ‘mojo,’ Austin must return to the swingin' '60s himself - with the help of American agent, Felicity Shagwell - to stop the dastardly plan. Once there, Austin faces off against Dr. Evil's army of minions to try to save the world in his own unbelievably groovy way.",
        poster_path: "/wqcE8EAmVl5j3mLuIrHFG7RmQyg.jpg",
        release_year: 1999,
    },
    {
        title: "Shrek",
        rating: 7.6,
        genre: 'Family',
        plot: "It ain't easy bein' green -- especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an unlikely compatriot -- a wisecracking donkey.",
        poster_path: "/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
        release_year: 2001,
    },
    {
        title: "Austin Powers: International Man of Mystery",
        rating: 6.5,
        genre: 'Comedy',
        plot: "As a swingin' fashion photographer by day and a groovy British superagent by night, Austin Powers is the '60s' most shagadelic spy, baby! But can he stop megalomaniac Dr. Evil after the bald villain freezes himself and unthaws in the '90s? With the help of sexy sidekick Vanessa Kensington, he just might.",
        poster_path: "/qSvfLwdDBLjZaPwA7qdn0yYePq5.jpg",
        release_year: 1997,
    },
    {
        title: "Austin Powers in Goldmember",
        rating: 5.9,
        genre: 'Comedy',
        plot: "The world's most shagadelic spy continues his fight against Dr. Evil. This time, the diabolical doctor and his clone, Mini-Me, team up with a new foe—'70s kingpin Goldmember. While pursuing the team of villains to stop them from world domination, Austin gets help from his dad and an old girlfriend.",
        poster_path: "/c4Sus7BvVQM6i9M3Cr0U8Vw0L9f.jpg",
        release_year: 2002,
    },
    {
        title: "Harry Potter and the Chamber of Secrets",
        rating: 7.7,
        genre: 'Adventure',
        plot: "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
        poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
        release_year: 2002,
    },
    {
        title: "Harry Potter and the Prisoner of Azkaban",
        rating: 8.0,
        genre: 'Adventure',
        plot: "Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.",
        poster_path: "/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
        release_year: 2004,
    },
    {
        title: "Meet the Fockers",
        rating: 6.2,
        genre: 'Comedy',
        plot: "Hard-to-crack ex-CIA man, Jack Byrnes and his wife, Dina head for the warmer climes of Florida to meet son-in-law-to-be, Greg Focker's parents. Unlike their happily matched offspring, the future in-laws find themselves in a situation of opposites that definitely do not attract.",
        poster_path: "/yr63jamc8NuEXUNQPX1fyjoEF2Q.jpg",
        release_year: 2004,
    },
    {
        title: "DodgeBall: A True Underdog Story",
        rating: 6.2,
        genre: 'Comedy',
        plot: "When megalomaniacal White Goodman, the owner of a trendy, high-end fitness center, makes a move to take over the struggling local gym run by happy-go-lucky Pete La Fleur, there's only one way for La Fleur to fight back: dodgeball. Aided by a dodgeball guru and Goodman's attorney, La Fleur and his rag-tag team of underdogs launch a knock-down, drag-out battle in which the winner takes all.",
        poster_path: "/yEOVrTOvVFtd0hsw2Sjfm2t6aVn.jpg",
        release_year: 2004,
    },
    {
        title: "Johnny English",
        rating: 6.2,
        genre: 'Comedy',
        plot: "A lowly pencil pusher working for MI7, Johnny English is suddenly promoted to super spy after Agent One is assassinated and every other agent is blown up at his funeral. When a billionaire entrepreneur sponsors the exhibition of the Crown Jewels—and the valuable gems disappear on the opening night and on English's watch—the newly-designated agent must jump into action to find the thief and recover the missing gems.",
        poster_path: "/vxWakJalIcLO1J8yyFEOVQzuLsv.jpg",
        release_year: 2003,
    },
    {
        title: "The Dictator",
        rating: 6.1,
        genre: 'Comedy',
        plot: "The heroic story of a dictator who risks his life to ensure that democracy would never come to the country he so lovingly oppressed.",
        poster_path: "/7NkfBiQWyCL3HPOskZNgcFslyCr.jpg",
        release_year: 2012,
    },
    {
        title: "Harold & Kumar Escape from Guantanamo Bay",
        rating: 6.2,
        genre: 'Comedy',
        plot: "Having satisfied their urge for White Castle, Harold and Kumar jump on a plane to catch up with Harold's love interest, who's headed for the Netherlands. But the pair must change their plans when Kumar is accused of being a terrorist. Rob Corddry also stars in this wild comedy sequel that follows the hapless stoners' misadventures as they try to avoid being captured by the Department of Homeland Security.",
        poster_path: "/pRo2wOKbJEfoLnTK1APcDtKfGzL.jpg",
        release_year: 2008,
    },
    {
        title: "Ace Ventura: Pet Detective",
        rating: 6.5,
        genre: 'Comedy',
        plot: "He's Ace Ventura: Pet Detective. Jim Carrey is on the case to find the Miami Dolphins' missing mascot and quarterback Dan Marino. He goes eyeball to eyeball with a man-eating shark, stakes out the Miami Dolphins and woos and wows the ladies. Whether he's undercover, under fire or underwater, he always gets his man… or beast!",
        poster_path: "/pqiRuETmuSybfnVZ7qyeoXhQyN1.jpg",
        release_year: 1994,
    },
    {
        title: "Space Jam",
        rating: 6.8,
        genre: 'Family',
        plot: "Jokes fly as the Tune Squad takes on the Nerdlucks in a hardcourt game to decide if the Looney Tunes remain here... or become attractions at a far-off galactic off-ramp called Moron Mountain. The Nerdlucks have a monstrous secret weapon: they've stolen the skills of top NBA stars like Charles Barkley and Patrick Ewing and become Monstars. But that's not all, folks. The Tune Squad’s secret weapon just happens to be the finest player in this or any other universe. He's outta this world. So's the fun.",
        poster_path: "/4RN5El3Pj2W4gpwgiAGLVfSJv2g.jpg",
        release_year: 1996,
    },
    {
        title: "Saw",
        rating: 7.3,
        genre: 'Horror',
        plot: "Obsessed with teaching his victims the value of life, a deranged, sadistic serial killer abducts the morally wayward. Once captured, they must face impossible choices in a horrific game of survival. The victims must fight to win their lives back, or die trying...",
        poster_path: "/pparEGTCxcTiImyVFoKD0LX11N8.jpg",
        release_year: 2004,
    },
    {
        title: "The Matrix Reloaded",
        rating: 6.9,
        genre: 'Thriller',
        plot: "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
        poster_path: "/8xEVAe84zlL9rkfYT6dZXero4KK.jpg",
        release_year: 2003,
    },
    {
        title: "No Country for Old Men",
        rating: 7.9,
        genre: 'Action',
        plot: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
        poster_path:  "/6d5XOczc226jECq0LIX0siKtgHR.jpg",
        release_year: 2007,
    },
    {
        title: "Pokémon: The First Movie - Mewtwo Strikes Back",
        rating: 6.8,
        genre: 'Family',
        plot: "The adventure explodes into action with the debut of Mewtwo, a bio-engineered Pokémon created from the DNA of Mew, the rarest of all Pokémon. Determined to prove its superiority, Mewtwo lures Satoshi, Pikachu and others into a Pokémon match like none before. Mewtwo vs. Mew. Super-clones vs. Pokémon. It's the ultimate showdown ... with the very future of the world at stake!",
        poster_path: "/3m1kyUksL3vf4anbYMbLUWXTb3W.jpg",
        release_year: 1998,
    },
    {
        title: "Bridesmaids",
        rating: 6.5,
        genre: 'Comedy',
        plot: "Annie's life is a mess. But when she finds out her lifetime best friend is engaged, she simply must serve as Lillian's maid of honor. Though lovelorn and broke, Annie bluffs her way through the expensive and bizarre rituals. With one chance to get it perfect, she’ll show Lillian and her bridesmaids just how far you’ll go for someone you love.",
        poster_path: "/cruSkSZJEmv9pbDoHBwdHdsnvHO.jpg",
        release_year: 2011,
    },
    {
        title: "A Fairly Odd Movie: Grow Up, Timmy Turner!",
        rating: 5.0,
        genre: 'Family',
        plot: "The television movie is set in the city of Dimmsdale and centers on the series' main protagonist Timmy Turner with his fairy godparents Cosmo and Wanda and his fairy godbrother Poof. In the movie, Timmy is now 23 years old but is still in fifth grade with his fairy-obsessed fifth grade teacher Mr. Crocker. Despite being grown up, Timmy finds a loophole in the fairy rulebook Da Rules: if he continues to act like a kid, he will still get to keep his fairies. However, the dilemma rises when Tootie, who was once a dorky girl when she was 10 years old, returns to Dimmsdale as an attractive woman. Timmy falls in love with her, a sign that he is growing up to an adult, which means he is closer to losing his fairies. Meanwhile, an oil business tycoon named Hugh J. Magnate, Jr., who teams up with Mr. Crocker, plans to use Timmy's fairies' magic in order to promote his oil business.",
        poster_path: "/lyLGhBZ4ljApZIp7SSnfAHvrG9w.jpg",
        release_year: 2011,
    },
    {
        title: "Pokémon 3: The Movie - Spell of the Unown",
        rating: 6.4,
        genre: 'Family',
        plot: "When Me Snowdon's sadness of her father's disappearance get to her, she unknowingly uses the Unknown to create her own dream world along with Entei, who she believes to be her father. When Entei kidnaps Satoshi's mother, Satoshi along with Kasumi & Takeshi invade the mansion looking for his mom and trying to stop the mysteries of Me's Dream World and Entei!",
        poster_path: "/g2C95ubS56O1ITXy1MgC69kAwF0.jpg",
        release_year: 2000,
    },
    {
        title: "Kangaroo Jack",
        rating: 5.1,
        genre: 'Comedy',
        plot: "Two childhood friends — a New York hairstylist and a wanna-be musician — get mixed-up with the mob and are forced to deliver $50,000 to Australia, but things go all wrong when the money is lost to a wild kangaroo.",
        poster_path: "/nflh9On0de4l7ItCl3n4NVXjmnm.jpg",
        release_year: 2003,
    },
    {
        title: "Sherlock Holmes",
        rating: 7.1,
        genre: 'Action',
        plot: "Eccentric consulting detective, Sherlock Holmes and Doctor John Watson battle to bring down a new nemesis and unravel a deadly plot that could destroy England.",
        poster_path: "/momkKuWburNTqKBF6ez7rvhYVhE.jpg",
        release_year: 2009,
    },
    {
        title: "The Cat in the Hat",
        rating: 5.3,
        genre: 'Comedy',
        plot: "Conrad and Sally Walden are home alone with their pet fish. It is raining outside, and there is nothing to do. Until The Cat in the Hat walks in the front door. He introduces them to their imagination, and at first it's all fun and games, until things get out of hand, and The Cat must go, go, go, before their parents get back.",
        poster_path: "/vyaJdKBxnLXZOmcB3Tqd5FiB9wA.jpg",
        release_year: 2003,
    },
    {
        title: "Inception",
        rating: 8.3,
        genre: 'Thriller',
        plot: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception, the implantation of another person's idea into a target's subconscious.",
        poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        release_year: 2010,
    },
    {
        title: "Pokémon: Destiny Deoxys",
        rating: 6.5,
        genre: 'Family',
        plot: "A comet bearing a deadly Pokemon creature crash-lands onto Earth, terrorising a nearby high-tech city, where Ash, Pikachu and friends are currently visiting...",
        poster_path: "/uEeLCGLIXH1ElS53hyUQInJB0Ub.jpg",
        release_year: 2004,
    },
    {
        title: "Pokémon: Lucario and the Mystery of Mew",
        rating: 6.9,
        genre: 'Family',
        plot: "In the legendary past, before Poké Balls were invented, an aura-guiding hero Pokémon named Lucario sensed two groups of armies about to clash, and a threat of a massive war in front of Oldoran Castle in Kanto that would leave no survivors. He transferred this message to his master, the legendary hero Arlon, while he was being attacked by a violent group of Hellgar. During the battle, his sense of sight was lost and he was rendered unable to see. He used the detection of his Aura, and so with the offensive Wave Bomb, he eliminated them. Though by the threat, the queen of Rota, Lady Rin was resolute to die with her civilians, and so Arlon made a choice.",
        poster_path: "/612lsEOZvsn3ELh07OGGGKCeEVj.jpg",
        release_year: 2005,
    },
    {
        title: "The Pink Panther 2",
        rating: 5.7,
        genre: 'Comedy',
        plot: "When legendary treasures from around the world are stolen, including the priceless Pink Panther Diamond, Chief Inspector Dreyfus is forced to assign Inspector Clouseau to a team of international detectives and experts charged with catching the thief and retrieving the stolen artifacts.",
        poster_path: "/1XI20rOfPL6i9DrbO6GRWRxlQ60.jpg",
        release_year: 2009,
    },
    {
        title: "Street Fighter",
        rating: 4.5,
        genre: 'Action',
        plot: "Col. Guile and various other martial arts heroes fight against the tyranny of Dictator M. Bison and his cohorts.",
        poster_path: "/4ZJY8OSYtSQ5E0isMgjEesGN0re.jpg",
        release_year: 1994,
    },
    {
        title: "John Wick: Chapter 3 - Parabellum",
        rating: 7.4,
        genre: 'Aciton',
        plot: "Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
        poster_path: "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
        release_year: 2019,
    },
    {
        title: "It",
        rating: 7.2,
        genre: 'Horror',
        plot: "In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.",
        poster_path: "/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
        release_year: 2017,
    },
    {
        title: "Suicide Squad",
        rating: 5.9,
        genre: 'Action',
        plot: "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences.",
        poster_path: "/xFw9RXKZDvevAGocgBK0zteto4U.jpg",
        release_year: 2016,
    },
    {
        title: "Aladdin",
        rating: 7.1,
        genre: 'Family',
        plot: "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
        poster_path: "/ykUEbfpkf8d0w49pHh0AD2KrT52.jpg",
        release_year: 2019,
    },
    {
        title: "The Lion King",
        rating: 7.1,
        genre: 'Family',
        plot: "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
        poster_path: "/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
        release_year: 2019,
    },
    {
        title: "Pokémon the Movie: I Choose You!",
        rating: 7.0,
        genre: 'Family',
        plot: "Ash Ketchum wakes up late one morning after having broken his alarm clock in his sleep. He eventually makes it to Professor Oak's lab, but is told that the three starter List of Pokémon (Bulbasaur, Squirtle, and Charmander) have already been taken by Trainers who were on time. However, Oak reveals that he has one more Pokémon, an Electric-type named Pikachu. Despite its volatile and feisty personality, as well as its refusal to get inside a Poké Ball, Ash happily takes Pikachu for his journey.",
        poster_path: "/cmpOaiRtjnhLNF2iPslMXCOcVJ.jpg",
        release_year: 2017,
    },
    {
        title: "Containment",
        rating: 5.9,
        genre: 'Thriller',
        plot: "Neighbors in a block wake one morning to find they have been sealed inside their apartments. Can they work together to find out why? Or will they destroy each other in their fight to escape?",
        poster_path: "/jMyudM6LM9VfIsR8ZRghlSpAdfv.jpg",
        release_year: 2015,
    },
    {
        title: "Monster House",
        rating: 6.6,
        genre: 'Horror',
        plot: "Monsters under the bed are scary enough, but what happens when an entire house is out to get you? Three teens aim to find out when they go up against a decrepit neighboring home and unlock its frightening secrets.",
        poster_path: "/zCRPr4bkO3ae0U1134vJ39xZnAG.jpg",
        release_year: 2006,
    },
    {
        title: "Beverly Hills Cop III",
        rating: 5.8,
        genre: 'Comedy',
        plot: "Back in sunny southern California and on the trail of two murderers, Axel Foley again teams up with LA cop Billy Rosewood. Soon, they discover that an amusement park is being used as a front for a massive counterfeiting ring – and it's run by the same gang that shot Billy's boss.",
        poster_path: "/5vpUjm2wnR2cyrqEhpJTsu1pfhg.jpg",
        release_year:1994,
    },

];

const seedMovies = () => Movie.bulkCreate(movies)
seedMovies();

module.exports= seedMovies;


// {
//     title: 
//     rating: ,
//     genre: '',
//     plot: 
//     poster_path: 
//     release_year: ,
// },